const Map<String, String> en = {
  'about_title': 'About Us',
  'about_desc': 'We provide the best manpower services globally.',
  'about_mission_label': 'Our Mission:',
  'about_vision_label': 'Our Vision:',
  'services_title': 'Our Services',
  'services_no_services': 'No Services Available',
  'healthcare': 'Healthcare Staffing',
  'security': 'Security Services',
  'housekeeping': 'Housekeeping Services',
  'corporate': 'Corporate Staffing',
  'skilled_labour': 'Skilled Labour Solutions',
  'unskilled_labour': 'Unskilled Labour Support',
  'facility_management': 'Facility Management',
  'home_section_title': 'Why CrewmanPower?',
  'home_feature_why_choose': 'Trusted Expertise',
  'home_feature_why_choose_desc':
      'Delivering staffing excellence across healthcare, hospitality, and corporate sectors.',
  'home_feature_services': 'Comprehensive Service Range',
  'home_feature_services_desc':
      'From healthcare support to corporate manpower, we cover all staffing needs.',
  'home_feature_industries': 'Diverse Industry Coverage',
  'home_feature_industries_desc':
      'Staffing solutions tailored for the industries that matter most to your business.',
  'about_intro_title': 'Meet the team behind reliable manpower delivery.',
  'hospital': 'Hospital',
  'nav_home': 'Home',
  'nav_about': 'About Us',
  'nav_services': 'Services',
  'nav_industries': 'Industries',
  'nav_careers': 'Careers',
  'nav_contact': 'Contact Us',
  'menu_title': 'Menu',
  'hero_badge': 'GLOBAL MANPOWER & STAFFING',
  'hero_title': 'Your Trusted Partner for Elite Talent Recruitment',
  'hero_subtitle':
      'We connect top corporate enterprises and healthcare institutions with world-class skilled manpower solutions efficiently.',
  'hero_hire_button': 'Hire Staff Now',
  'hero_apply_button': 'Apply for Jobs',
  'contact_appbar': 'Contact & Inquiries',
  'contact_tab_hospital': 'Hospital Staffing Form',
  'contact_tab_corporate': 'Corporate Staffing Form',
  'contact_request': 'Request {type} Manpower Staff',
  'contact_name_label': 'Organization / Full Name',
  'contact_phone_label': 'Phone Number',
  'contact_message_label': 'Requirements Detail',
  'contact_submit': 'Submit Inquiry',
  'contact_success_snack': 'Inquiry Submitted Successfully!',
  'contact_quick_call': 'Call Now',
  'contact_quick_email': 'Email',
  'contact_quick_chat': 'WhatsApp / Chat',
  'career_title': 'Careers / Job Openings',
  'career_apply_now': 'Apply Now',
  'career_no_jobs': 'No jobs available.',
  'career_apply_dialog_title': 'Apply for {jobTitle}',
  'career_full_name': 'Full Name',
  'career_email': 'Email',
  'career_upload_resume': 'Upload Resume (PDF)',
  'cancel': 'Cancel',
  'submit': 'Submit',
  'industries_title': 'INDUSTRIES WE CATER',
  'industries_subtitle':
      'Providing world-class staffing solutions across diverse sectors.',
  'industry_hospital_healthcare': 'Hospital & Healthcare',
  'industry_hotels_hospitality': 'Hotels & Hospitality',
  'industry_warehouses_logistics': 'Warehouses & Logistics',
  'industry_corporate_offices': 'Corporate Offices',
  'industry_security_surveillance': 'Security & Surveillance',
  'industry_manufacturing_factories': 'Manufacturing & Factories',
  'no_data_available': 'No Data Available',
  'testimonials_title': 'What Our Clients Say',
  'faq_title': 'Frequently Asked Questions',
  'error_loading_content': 'Error loading content',
};
