const Map<String, String> hi = {
  'about_title': 'हमारे बारे में',
  'about_desc':
      'हम वैश्विक स्तर पर सर्वश्रेष्ठ जनशक्ति सेवाएं प्रदान करते हैं।',
  'about_mission_label': 'हमारा मिशन:',
  'about_vision_label': 'हमारी दृष्टि:',
  'services_title': 'हमारी सेवाएँ',
  'services_no_services': 'कोई सेवा उपलब्ध नहीं है',
  'healthcare': 'स्वास्थ्य सेवा स्टाफिंग',
  'security': 'सुरक्षा सेवाएँ',
  'housekeeping': 'हाउसकीपिंग सेवाएँ',
  'corporate': 'कॉर्पोरेट स्टाफिंग',
  'skilled_labour': 'कुशल मजदूरी समाधान',
  'unskilled_labour': 'अकुशल मजदूरी सहायता',
  'facility_management': 'सुविधा प्रबंधन',
  'home_section_title': 'क्यों CrewmanPower?',
  'home_feature_why_choose': 'विश्वसनीय विशेषज्ञता',
  'home_feature_why_choose_desc':
      'हम स्वास्थ्य देखभाल, आतिथ्य और कॉर्पोरेट क्षेत्रों में स्टाफिंग उत्कृष्टता प्रदान करते हैं।',
  'home_feature_services': 'विस्तृत सेवा रेंज',
  'home_feature_services_desc':
      'स्वास्थ्य देखभाल समर्थन से कॉर्पोरेट मानवशक्ति तक, हम सभी स्टाफिंग आवश्यकताओं को कवर करते हैं।',
  'home_feature_industries': 'विविध उद्योग कवरेज',
  'home_feature_industries_desc':
      'आपके व्यवसाय के लिए सबसे महत्वपूर्ण उद्योगों के लिए तैयार स्टाफिंग समाधान।',
  'about_intro_title': 'विश्वसनीय मानवशक्ति वितरण के पीछे की टीम से मिलें।',
  'hospital': 'अस्पताल',
  'nav_home': 'होम',
  'nav_about': 'हमारे बारे में',
  'nav_services': 'सेवाएँ',
  'nav_industries': 'उद्योग',
  'nav_careers': 'करियर',
  'nav_contact': 'संपर्क करें',
  'menu_title': 'मेनू',
  'hero_badge': 'वैश्विक मानवशक्ति और स्टाफिंग',
  'hero_title': 'सर्वोत्तम प्रतिभा भर्ती के लिए आपका विश्वसनीय साझेदार',
  'hero_subtitle':
      'हम शीर्ष कॉर्पोरेट उद्यमों और स्वास्थ्य देखभाल संस्थानों को विश्व स्तर की कुशल मानवशक्ति समाधान से जोड़ते हैं।',
  'hero_hire_button': 'कर्मचारियों को हायर करें',
  'hero_apply_button': 'नौकरी के लिए आवेदन करें',
  'contact_appbar': 'संपर्क और पूछताछ',
  'contact_tab_hospital': 'अस्पताल स्टाफिंग फॉर्म',
  'contact_tab_corporate': 'कॉर्पोरेट स्टाफिंग फॉर्म',
  'contact_request': '{type} मानवशक्ति स्टाफ का अनुरोध करें',
  'contact_name_label': 'संगठन / पूरा नाम',
  'contact_phone_label': 'फोन नंबर',
  'contact_message_label': 'आवश्यकताओं का विवरण',
  'contact_submit': 'पूछताछ भेजें',
  'contact_success_snack': 'पूछताछ सफलतापूर्वक भेजी गई!',
  'contact_quick_call': 'अब कॉल करें',
  'contact_quick_email': 'ईमेल',
  'contact_quick_chat': 'व्हाट्सएप / चैट',
  'career_title': 'करियर / नौकरी के अवसर',
  'career_apply_now': 'अब आवेदन करें',
  'career_no_jobs': 'कोई नौकरियां उपलब्ध नहीं हैं।',
  'career_apply_dialog_title': '{jobTitle} के लिए आवेदन करें',
  'career_full_name': 'पूरा नाम',
  'career_email': 'ईमेल',
  'career_upload_resume': 'रिज़्यूम अपलोड करें (PDF)',
  'cancel': 'रद्द करें',
  'submit': 'जमा करें',
  'industries_title': 'हम किन उद्योगों की सेवा करते हैं',
  'industries_subtitle':
      'विभिन्न क्षेत्रों में विश्वस्तरीय स्टाफिंग समाधान प्रदान करना।',
  'industry_hospital_healthcare': 'अस्पताल और स्वास्थ्य सेवा',
  'industry_hotels_hospitality': 'होटल और आतिथ्य',
  'industry_warehouses_logistics': 'वेयरहाउस और रसद',
  'industry_corporate_offices': 'कॉर्पोरेट कार्यालय',
  'industry_security_surveillance': 'सुरक्षा और निगरानी',
  'industry_manufacturing_factories': 'निर्माण और कारखाने',
  'no_data_available': 'कोई डेटा उपलब्ध नहीं है',
  'testimonials_title': 'हमारे ग्राहक क्या कहते हैं',
  'faq_title': 'अक्सर पूछे जाने वाले प्रश्न',
  'error_loading_content': 'सामग्री लोड करने में त्रुटि',
};
