const Map<String, String> ur = {
  'about_title': 'ہمارے بارے میں',
  'about_desc': 'ہم عالمی سطح پر بہترین افرادی قوت کی خدمات فراہم کرتے ہیں۔',
  'about_mission_label': 'ہمارا مشن:',
  'about_vision_label': 'ہماری وژن:',
  'services_title': 'ہماری خدمات',
  'services_no_services': 'کوئی خدمات دستیاب نہیں ہیں',
  'healthcare': 'ہیلتھ کیئر اسٹافنگ',
  'security': 'سیکیورٹی خدمات',
  'housekeeping': 'ہاؤس کیپنگ خدمات',
  'corporate': 'کارپوریٹ اسٹافنگ',
  'skilled_labour': 'ماہر مزدوری حل',
  'unskilled_labour': 'غیر ماہر مزدوری معاونت',
  'facility_management': 'فیسلٹی مینجمنٹ',
  'home_section_title': 'کیوں CrewmanPower؟',
  'home_feature_why_choose': 'قابل اعتماد مہارت',
  'home_feature_why_choose_desc':
      'ہم صحت کی دیکھ بھال، میزبانی اور کارپوریٹ شعبوں میں اسٹافنگ میں بہترین خدمات فراہم کرتے ہیں۔',
  'home_feature_services': 'وسیع خدمات',
  'home_feature_services_desc':
      'ہیلتھ کیئر سپورٹ سے کارپوریٹ مین پاور تک، ہم تمام اسٹافنگ ضروریات کو پورا کرتے ہیں۔',
  'home_feature_industries': 'متنوع صنعتوں کا احاطہ',
  'home_feature_industries_desc':
      'آپ کے کاروبار کے لئے سب سے زیادہ اہم صنعتوں کے لئے تیار کردہ اسٹافنگ حل۔',
  'about_intro_title': 'قابل اعتماد انسانی قوت کی فراہمی کے پیچھے ٹیم سے ملیں۔',
  'hospital': 'ہسپتال',
  'nav_home': 'ہوم',
  'nav_about': 'ہمارے بارے میں',
  'nav_services': 'خدمات',
  'nav_industries': 'صنعتیں',
  'nav_careers': 'کیریئر',
  'nav_contact': 'ہم سے رابطہ کریں',
  'menu_title': 'مینو',
  'hero_badge': 'عالمی مین پاور اور اسٹافنگ',
  'hero_title': 'اعلیٰ صلاحیت بھرتی کے لئے آپ کا قابل اعتماد پارٹنر',
  'hero_subtitle':
      'ہم اعلیٰ کارپوریٹ اور طبی اداروں کو ماہر افرادی قوت کے حل سے جوڑتے ہیں۔',
  'hero_hire_button': 'اب ملازمین رکھیں',
  'hero_apply_button': 'ملازمت کے لئے درخواست دیں',
  'contact_appbar': 'رابطہ اور استفسار',
  'contact_tab_hospital': 'ہسپتال اسٹافنگ فارم',
  'contact_tab_corporate': 'کارپوریٹ اسٹافنگ فارم',
  'contact_request': '{type} مین پاور اسٹاف کی درخواست کریں',
  'contact_name_label': 'تنظیم / پورا نام',
  'contact_phone_label': 'فون نمبر',
  'contact_message_label': 'ضروریات کی تفصیل',
  'contact_submit': 'استفسار جمع کریں',
  'contact_success_snack': 'استفسار کامیابی کے ساتھ بھیج دی گئی!',
  'contact_quick_call': 'اب کال کریں',
  'contact_quick_email': 'ای میل',
  'contact_quick_chat': 'واٹس ایپ / چیٹ',
  'career_title': 'کیریئر / ملازمت کے مواقع',
  'career_apply_now': 'اب درخواست دیں',
  'career_no_jobs': 'کوئی ملازمتیں دستیاب نہیں ہیں۔',
  'career_apply_dialog_title': '{jobTitle} کے لئے درخواست دیں',
  'career_full_name': 'پورا نام',
  'career_email': 'ای میل',
  'career_upload_resume': 'ریزیومے اپ لوڈ کریں (PDF)',
  'cancel': 'منسوخ کریں',
  'submit': 'جمع کریں',
  'industries_title': 'ہم کن صنعتوں کی خدمات فراہم کرتے ہیں',
  'industries_subtitle':
      'متنوع شعبوں میں عالمی معیار کے اسٹافنگ حل فراہم کرنا۔',
  'industry_hospital_healthcare': 'ہسپتال اور صحت کی دیکھ بھال',
  'industry_hotels_hospitality': 'ہوٹلز اور میزبانی',
  'industry_warehouses_logistics': 'گودام اور لاجسٹکس',
  'industry_corporate_offices': 'کارپوریٹ دفاتر',
  'industry_security_surveillance': 'سیکیورٹی اور نگرانی',
  'industry_manufacturing_factories': 'مینوفیکچرنگ اور فیکٹریاں',
  'no_data_available': 'کوئی ڈیٹا دستیاب نہیں ہے',
  'testimonials_title': 'ہمارے کلائنٹ کیا کہتے ہیں',
  'faq_title': 'اکثر پوچھے جانے والے سوالات',
  'error_loading_content': 'مواد لوڈ کرنے میں خرابی',
};
